### PR TITLE
Set Up Travis

### LINKED ISSUE #47: Set up Travis for CI/CD
In a nutshell:
**Continuous Integration (CI):** The practice of merging your incremental changes into the codebase frequently. This practically implies having your code built and tested automatically when trying to merge your code (creating a pull request). This prevents checking in code that breaks the product.

**Continuous Delivery (CD):** The practice of deploying the latest changes to production automatically upon checking in code.
More: https://stackoverflow.com/a/48477591/1768702.

**Travis:** Popular CI/CD service that is free for open source projects on Github, so great for our use case. More: https://docs.travis-ci.com/. You can basically opt in with your Github account (project admin only can do this), then add a travis.yml file to the repository root with the steps to build and test the code.

Setting up a CI/CD solution is essential for working on quality code. If anyone is interested we can discuss this here.

### PR DESCRIPTION
**Pull request by lealgamb**
Added the `.travis.yml` file.

"Fixes #47 "

### CODE REVIEW

**Comment by yebrahim** [comment]
Nice!
You can see the extra pieces of UI in this PR: The Checks tab now has 4 new checks in it, and a new line in the PR status at the end of the PR, where the merge button is. If you show all checks, you can follow the continuous-integration/<branch_name> Details links to see the Travis logs. This is an example: https://travis-ci.com/vocatwk/CodeU-Nemo/builds/75974460

As you can see from the logs, it looks like all we needed to do was specify that this is a Java project (your one-line travis file), and the Travis VM automatically ran the mvn build and tests. After this is merged, any other PR with failing tests will result in a red signal from Travis to Github.

The remaining step now is to block merging PRs if Travis is reporting an error. @vocatwk will need to help with this. You'll need to look for branch settings for this repo, and enable branch protection for the master branch, and require Travis green status. Something like:

image

**Comment by yebrahim** [comment]
Tip: Add the string: "Fixes #47" to the description of this PR before merging. :)

**Comment by yebrahim** [comment]
@vocatwk can you take care of changing the settings like we discussed above?
@lealgamb nice! btw, you don't need the quotes around "Fixes #47" :)

**Comment by vocatwk** [comment]
I just changed the settings. Do the above two need to be ticked as well?
screen shot 2018-06-14 at 9 27 53 am

**Comment by yebrahim** [comment]
I think this should be enough, the other two are the same thing as this one as far as I can see.
We'll see what happens the next PR. :)

Thanks @vocatwk.

**Pull request merged**
