### PR TITLE
Navbar collapses

### PR DESCRIPTION
**Pull request by lealgamb**
The navbar now collapses on smaller screen sizes. 
image

However, I ran into a problem with the search bar results. When the first result is clicked, it triggers the dropdown menu instead.
image

### CODE REVIEW

**Comment by vocatwk** [comment]
Could we have the drop down positioned somewhere else when it collapses?

**Comment by lealgamb** [comment]
An easy fix would be to move the dropdown menu to the left of the search bar. Or to move it as far left as possible next to the other navbar items. I personally like it on the right side, but this could be an alternative if you guys are okay with this.

**Comment by vocatwk** [comment]
I'm okay with it if it's giving you a lot of trouble.

**Comment by jasminechau2** [comment]
Do what you need to do

**Comment by lealgamb** [comment]
Alright, thanks.

What do you guys prefer? 
image

or
image

**Comment by jasminechau2** [comment]
I like the first one

**Comment by vocatwk** [comment]
same here. I like the first better.

**Pull request merged**
