### PR TITLE
Screenshot on README

### PR DESCRIPTION
**Pull request by lealgamb**
Feel free to suggest other screenshots to include.

### CODE REVIEW

**Comment by jasminechau2** [comment]
what is it a screen shot of

**Comment by jasminechau2** [comment]
Also can you add in the notifcation page in the README?

**Comment by lealgamb** [comment]
https://github.com/vocatwk/CodeU-Nemo/tree/ReadMe

**Comment by jasminechau2** [comment]
Ohh I see nice!

**Comment by vocatwk** [comment]
Can you add:
* Nemo allows you to add/remove users from a conversation
* Nemo keeps your conversations safe by allowing only members access

**Comment by lealgamb** [comment]
@jasminechau2 is there anything specific you want me to add for the notifications?

**Comment by jasminechau2** [comment]
Nemo features a notification page that allows you to see when messages and conversations are being made

**Comment by lealgamb** [comment]
All good?

**Comment by vocatwk** [comment]
Yup

**Comment by jasminechau2** [comment]
LGTM

**Comment by yebrahim** [comment]
This is awesome! You all did a great job here, I'm really proud of the result in such a short time!
🎆 🎉 🎈

**Pull request merged**
